services:
  - type: web
    name: coffee-ni-jeem-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    buildCommand: echo "Building with Docker"
    startCommand: echo "Starting with Docker"
    envVars:
      - key: APP_NAME
        value: Coffee Ni Jeem
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: coffee-ni-jeem-backend
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: coffee-ni-jeem-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: coffee-ni-jeem-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: coffee-ni-jeem-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: coffee-ni-jeem-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: coffee-ni-jeem-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: your-email@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: noreply@your-domain.com
      - key: MAIL_FROM_NAME
        value: Coffee Ni Jeem
      - key: SANCTUM_STATEFUL_DOMAINS
        value: brew-with-jeem.netlify.app

databases:
  - name: coffee-ni-jeem-db
    plan: starter
    region: oregon
